title: "Laura Vincoleto Zanfolim"
author: "Laura Vincoleto Zanfolim"
description: "University of SÃ£o Paulo" #color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home", icon: home}
  - {file: "README.md", title: "About me"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "lauravinzan@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/lauravinzan/lauravinzan"}
  - {title: Instagram, icon: rss, url: "https://www.instagram.com/lauravz.anv/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
